# Generated by Django 3.0.7 on 2020-07-31 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='Files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xlsb', 'xlsm', 'xltx', 'xltm', 'xls', 'xlt', 'xml'])]),
        ),
    ]
