# Generated by Django 3.0.7 on 2020-08-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200731_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
