# Generated by Django 3.0.7 on 2020-08-12 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapi', '0003_delete_filemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=100)),
                ('input_id', models.IntegerField()),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xlsb'])])),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
